import React from 'react'
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "S-Shopping - About",
    description: "Generated by create next app",
};
const AboutLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <div>
            {children}
        </div>
    )
}

export default AboutLayout
