import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
    title: "S-Shopping - Contact",
    description: "Generated by create next app",
};
const ContactLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <>
            {children}
        </>
    )
}

export default ContactLayout
